### ISSUE TITLE
Update the Docker image

### ISSUE THREAD

**Issue by JoshuaSmeda** [voxpupuli/puppet-catalog-diff-viewer#35]
Hi guys,

Could you kindly consider doing whatever is necessary to publish the latest version of the [Docker image ](https://hub.docker.com/r/camptocamp/puppet-catalog-diff-viewer)

The current one is 2 years old and is missing some features added.

Thanks in advance!

**Comment by JoshuaSmeda** [comment]
Bump

**Comment by ekohl** [comment]
It was transferred to Vox Pupuli and we certainly don't have access to the camptocamp namespace. We do have our own namespace and it does look like we have a release workflow already (https://github.com/voxpupuli/vox-pupuli-tasks/blob/c2c95b2ae15a450f53cbcd96a4b99fd7460ad9bb/.github/workflows/test-build-release.yml#L47-L55).

@bastelfreak is this a matter of just setting the secret in GH and making a new release (provided the workflow is in place)?

**Comment by tuxmea** [comment]
Any update on a new docker image under voxpupuli namespace?

**Comment by rwaffen** [comment]
container image is now build in github actions right here in the ci. container images also will be released here on ghcr.

master will always be tagged with `development`. Tagged releases will have their corresponding tag.
